name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt remove -y containerd containerd.io
          sudo apt autoremove -y
          sudo apt clean
          sudo apt update
          sudo apt install -y docker.io

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: '**/Dockerfile'
          push: true
          tags: myapp:$(GITHUB_SHA)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with Ansible
        run: |
          ansible-playbook -i inventory playbook.yml

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourAppServiceName'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'myapp:$(GITHUB_SHA)'
