name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker buildx build --file ./Dockerfile --iidfile /tmp/docker-build-push-sJvfhV/iidfile --tag myapp:${{ github.sha }} --metadata-file /tmp/docker-build-push-sJvfhV/metadata-file --push .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i inventory playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourAppServiceName'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '$(DOCKER_REGISTRY)/myapp:${{ github.sha }}'
