name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 40.82.207.123 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini docker.yml

      - name: Build Docker Image
        run: docker build -t my-nginx .

      - name: Save Docker Image
        run: docker save -o my-nginx.tar my-nginx

      - name: Copy Docker Image to VM
        run: scp -i ~/.ssh/id_rsa my-nginx.tar azureuser@40.82.207.123:/home/azureuser
